#ifndef INPUTCODES_H
#define INPUTCODES_H

#define NUM_GAMEPAD_BUTTON_CODES 14
#define NUM_KEY_CODES 98
#define NUM_MOUSE_BUTTON_CODES 3
#define NUM_GAMEPAD_ANALOG_CODES 6
#define NUM_MOUSE_ANALOG_CODES 3

enum GamepadButtonInputCodes
{
    //Gamepad Buttons
    BUTTON_A, BUTTON_B, BUTTON_X, BUTTON_Y, BUTTON_DPAD_UP, BUTTON_DPAD_DOWN, BUTTON_DPAD_LEFT, BUTTON_DPAD_RIGHT, BUTTON_LEFT_STICK, BUTTON_RIGHT_STICK,
    BUTTON_LEFT_BUMPER, BUTTON_RIGHT_BUMPER, BUTTON_START, BUTTON_BACK
};

enum KeyInputCodes
{
    //Space Bar, Letters, Numbers, Arrow Keys, Numpad,
    KEY_LALT, KEY_RALT, KEY_BACKSPACE, KEY_CAPS, KEY_LCTRL, KEY_RCTRL, KEY_ENTER, KEY_ESCAPE, KEY_SPACE, KEY_TAB, KEY_LSHIFT, KEY_RSHIFT,
    KEY_ARROW_UP, KEY_ARROW_DOWN, KEY_ARROW_LEFT, KEY_ARROW_RIGHT, KEY_INSERT, KEY_DELETE, KEY_HOME, KEY_END, KEY_PAGE_UP, KEY_PAGE_DOWN, KEY_PRINTSCREEN,

    KEY_0, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9,

    KEY_A, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J, KEY_K, KEY_L, KEY_M, KEY_N, KEY_O,
    KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T, KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,

    KEY_NUMPAD_0, KEY_NUMPAD_1, KEY_NUMPAD_2, KEY_NUMPAD_3, KEY_NUMPAD_4, KEY_NUMPAD_5, KEY_NUMPAD_6, KEY_NUMPAD_7, KEY_NUMPAD_8, KEY_NUMPAD_9,
    KEY_NUMPAD_DECIMAL, KEY_NUMPAD_ENTER, KEY_NUMPAD_ADD, KEY_NUMPAD_SUBTRACT, KEY_NUMPAD_MULTIPLY, KEY_NUMPAD_DIVIDE,

    KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12,

    KEY_COMMA, KEY_PERIOD, KEY_SLASH, KEY_SEMICOLON, KEY_QUOTE, KEY_LEFT_BRACKET, KEY_RIGHT_BRACKET, KEY_BACKSLASH, KEY_SQUIGGLE, KEY_DASH, KEY_EQUALS
};

enum MouseButtonInputCodes
{
    MOUSE_LEFT_BUTTON, MOUSE_RIGHT_BUTTON, MOUSE_MIDDLE_BUTTON
};

enum GamepadAnalogInputCodes
{
    //Gamepad Analogs
    LEFT_TRIGGER, RIGHT_TRIGGER, LEFT_STICK_X, LEFT_STICK_Y, RIGHT_STICK_X, RIGHT_STICK_Y
};

enum MouseAnalogInputCodes
{
    //Mouse Analogs
    MOUSE_WHEEL, MOUSE_X, MOUSE_Y
};
#endif
